# Generated by Django 6.0.5 on 2026-05-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeederDataRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=255)),
                ('ssid', models.CharField(max_length=50)),
                ('voltage', models.CharField(max_length=50)),
                ('feeder_name', models.CharField(max_length=255)),
                ('meter_no', models.CharField(max_length=50, unique=True)),
                ('mw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('mvar', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('mw_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('mvar_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('export_mw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('import_mw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('net_mw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('communication', models.CharField(blank=True, max_length=100, null=True)),
                ('rtc_time', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'FeederDataRaw',
            },
        ),
    ]
