# Generated by Django 6.0.5 on 2026-05-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFeederData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('rounded_rtc_time', models.DateTimeField()),
                ('avg_export_mw', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('avg_net_mw', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('sample_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'main_feeder_data',
            },
        ),
        migrations.AddField(
            model_name='feederdataraw',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
