# Generated by Django 6.0.5 on 2026-05-29 09:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_mainfeederdata_feederdataraw_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainfeederdata',
            old_name='rounded_rtc_time',
            new_name='round_off_time',
        ),
        migrations.RemoveField(
            model_name='feederdataraw',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feederdataraw',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feederdataraw',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='feederdataraw',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainfeederdata',
            name='feeder_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feederdataraw',
            name='meter_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mainfeederdata',
            name='date',
            field=models.DateField(default=datetime.date(2026, 5, 29)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mainfeederdata',
            unique_together={('station', 'feeder_name', 'date', 'round_off_time')},
        ),
    ]
