# Generated by Django 6.0.5 on 2026-05-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_rename_rounded_rtc_time_mainfeederdata_round_off_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feederdataraw',
            old_name='time',
            new_name='round_off_time',
        ),
    ]
