# Generated by Django 6.0.5 on 2026-05-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_rename_time_feederdataraw_round_off_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mainfeederdata',
            unique_together={('station', 'feeder_name', 'round_off_time')},
        ),
        migrations.RemoveField(
            model_name='mainfeederdata',
            name='date',
        ),
    ]
