# Generated by Django 6.0.5 on 2026-05-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_alter_mainfeederdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederdataraw',
            name='script_run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
