# Generated by Django 6.0.5 on 2026-05-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_feederdataraw_script_run_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfeederdata',
            name='sample_count',
        ),
    ]
