# Generated by Django 6.0.5 on 2026-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_remove_mainfeederdata_sample_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feederdataraw',
            name='round_off_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feederdataraw',
            name='script_run_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mainfeederdata',
            name='round_off_time',
            field=models.CharField(max_length=100),
        ),
    ]
